# 工作流名称
name: Build and Deploy

on:
  # 指明要运行的分支，跟上面配置保持一致
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 把分支拉出来
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # 指定node版本
      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: latest

      # 安装依赖，包括我们的 semantic-release 全套
      - name: Install
        run: |
          npm install

      # 打包你的插件/组件/库等等等
      - name: Build
        run: |
          npm run build

      # 安装 zip
      - name: Install zip
        uses: montudor/action-zip@v1

      # 执行 semantic-release 发布包
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
